version: '3.8'
services:
  web:
    container_name: iam-container
    image: iam-app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  db:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Admin12345
  