version: '3.8'
services:
  web:
    container_name: iam-container
    image: iam-app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sleep infinity
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*