version: '3.8'
services:
  web:
    container_name: brass-container
    image: brass-app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  db:
    container_name: brass-db_1
    image: mongo:5.0
    ports:
      - 27018:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Admin12345
  